config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'

  get 'flights/index'

  post 'bookings/new',	   to: 'bookings#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'flights#index'

  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]


end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, :foreign_key => "from_airport_id", class_name: "Flight"
	has_many :arriving_flights, :foreign_key => "to_airport_id", class_name: "Flight"

	def self.airport_codes
		Airport.find_by_sql("select distinct code from airports")
	end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers

	accepts_nested_attributes_for :passengers

end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :from_airport, :foreign_key => "from_airport_id", class_name: "Airport"
	belongs_to :to_airport, :foreign_key => "to_airport_id", class_name: "Airport"
	has_many :bookings

	def flight_date_formatted
     @flight_dates
    end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking

	validates_uniqueness_of :email


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@flight = Flight.find(params[:booking][:flight_id])
    @booking = @flight.bookings.build
  	@passenger_count = params[:booking][:passengers].to_i

  	@passenger_count.times{@booking.passengers.build}

  end

  def show
  	@booking_id = params[:id]
  	flight_id = Booking.find(@booking_id).flight_id
  	
  	@flight_info = Flight.find(flight_id)
  	
    @passengers = get_passengers

  end

  def create

    @booking = Booking.create(:flight_id=> booking_params[:flight_id])

  	number_of_passengers = passenger_params[:passengers_attributes].keys.count

    number_of_passengers.times do |index|
      pass_params = passenger_params[:passengers_attributes]["#{index}"]
      p = @booking.passengers.build(pass_params)
      p.save
    end

  	@flight_id = booking_params[:flight_id]

    redirect_to @booking
  
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,passengers_attributes: [:name, :email])
  end

  def passenger_params
  	params.require(:booking).permit(passengers_attributes: [:name, :email])
  end

  def get_passengers
    passenger_ids = Booking.find(@booking_id).passengers
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
  	@airport_codes = get_airport_codes
  	@flight_dates = get_flight_dates


  	@flights = find_flights
  end


  private

  def flight_params
  	params.permit(:from_airport, :to_airport, :passengers, :flight_date)
  end

  def find_flights
  	@flights = Flight.where("from_airport_id =? AND to_airport_id=? AND date =?", params[:from_airport], params[:to_airport], params[:flight_date])
  end

  def format_date(time)
  	date = Time.zone.parse(time)
  end

  def get_airport_codes
  	Airport.all.map{ |airport| [ airport.code, airport.id ] }
  end

  def get_flight_dates
  	flight_dates = Flight.all.map{ |flight| [flight.date.strftime("%m/%d/%Y"), flight.date  ] }.uniq
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookings/new.html.erb
<h1> Booking Page </h1>
<h2>Flight Information </h2>
<h3>From: <%= @flight.from_airport.code %> To: <%= @flight.to_airport.code %>
Date: <%= @flight.date.strftime("%B %d, %Y") %></h3>

<%= form_for(@booking) do |f|%>

<%= f.hidden_field :flight_id, :value => @flight.id %>

<h2> Passenger Information</h2>
<%= f.fields_for :passengers do |passenger_fields| %>
		<b> Passenger <%=passenger_fields.index+1%></b>
		<%= passenger_fields.label :name %>
		<%= passenger_fields.text_field :name %>

		<%= passenger_fields.label :email %>
		<%= passenger_fields.text_field :email %>
		<br>
	<%end%>

<%= f.submit 'submit booking' %>

<%end%>
	

app/views/bookings/show.html.erb
<h1>Confirmation Page</h1>

<h2>Flight Information</h2>
From: <%= @flight_info.from_airport.code %> To: <%= @flight_info.to_airport.code %>
Date: <%= @flight_info.date.strftime("%B %d, %Y") %>

<h2>Passenger Information</h2>
<% @passengers.each_entry do |passenger| %>
<ul>Name: <%=passenger.name %> Email: <%=passenger.email%></ul>
<%end%>

app/views/flights/index.html.erb
<h1>Flights</h1>
<%= form_tag("/flights", method: "get") do %>

<%= label_tag("From:") %>
<%= select_tag(:from_airport, options_for_select(@airport_codes)) %>

<%= label_tag("To:") %>
<%= select_tag(:to_airport, options_for_select(@airport_codes)) %>

<%= label_tag("Passengers:") %>
<%= select_tag(:passengers, options_for_select(1..4)) %>

<%= label_tag("Available dates:") %>
<%= select_tag "flight_date", options_for_select(@flight_dates) %>
<br>
<%= submit_tag 'find flights' %>
<%end%>
<br>

<% if !@flights.empty? %>
<h2>Available Flights</h2>
<%= form_for(:booking, url: bookings_new_path) do |f|%>
	<% @flights.each_entry do |flight| %>
		<li><%= f.radio_button :flight_id, flight.id %>
		<%= f.label :flight, flight.inspect %></li>

	<%end%>
	<%= f.hidden_field :passengers, :value => params[:passengers] %>
	<%= f.submit 'select flight' %>


<%end%>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flightbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>